name: SuperSpyGuard
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: 83VGKGSQUH
    SWIFT_VERSION: 5.9

targets:
  SuperSpyGuard:
    type: application
    platform: iOS
    sources:
      - path: SuperSpyGuard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.SuperSpyGuard
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: SuperSpyGuard/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    capabilities:
      backgroundModes:
        modes:
          - fetch
          - processing
      appGroups:
        groups:
          - group.com.tokyonasu.SuperSpyGuard
    dependencies:
      - target: SuperSpyGuardWidget

  SuperSpyGuardWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SuperSpyGuardWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.SuperSpyGuard.Widget
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: SuperSpyGuardWidget/Info.plist
    capabilities:
      appGroups:
        groups:
          - group.com.tokyonasu.SuperSpyGuard
